name: Dispatch

on:
  push:
    branches:
      - main
    paths:
      - "dispatch.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Deploy Routing Rules on GCloud
        uses: ocadotechnology/codeforlife-workspace/.github/actions/gcloud/deploy-app@main
        with:
          gcp-credentials: ${{ secrets.GCP_CREDENTIALS }}
          deploy-args: dispatch.yaml
