name: Test JavaScript Code

on:
  workflow_call:
    inputs:
      node-version:
        description: "The Node.js version to set up."
        type: number
        required: false
        default: 18
      working-directory:
        description: "The current working directory."
        type: string
        required: false
        default: "."
      codecov-slug:
        description: "The slug provided to Codecov for the coverage report."
        type: string
        required: false
        default: ${{ github.repository }}
      codecov-yml-path:
        description: "The path of the Codecov YAML file."
        type: string
        required: false
        default: "./codecov.yml"
    secrets:
      CODECOV_TOKEN:
        description: "The token used to gain access to Codecov."
        required: false

jobs:
  test-js-code:
    runs-on: ubuntu-latest
    env:
      OCADO_TECH_ORG_ID: 2088731
    steps:
      - name: 🌐 Set up JavaScript ${{ inputs.node-version }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/javascript/setup-environment@configure_js_services # TODO: set to @main
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          install-args: --production=false

      - name: 🔎 Check Code Format
        working-directory: ${{ inputs.working-directory }}
        run: yarn format:check

      - name: 🔎 Check Static Type Hints
        working-directory: ${{ inputs.working-directory }}
        run: yarn type-check

      - name: 🔎 Check Static Code
        working-directory: ${{ inputs.working-directory }}
        run: yarn lint

      - name: 🧪 Test Code Units
        working-directory: ${{ inputs.working-directory }}
        run: yarn test:coverage

      - name: 📈 Upload Coverage Reports to Codecov
        if: github.repository_owner_id == env.OCADO_TECH_ORG_ID
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ inputs.codecov-slug }}
          codecov_yml_path: ${{ inputs.codecov-yml-path }}
          working-directory: ${{ inputs.working-directory }}
          file: coverage/coverage-final.json
